											-- ## Section A: Level 1 (Basic Queries)
											-- *Focus: SELECT, FROM, WHERE, ORDER BY, GROUP BY*

use supply_chain;

-- Q1.  **Data Exploration:** Read all the data from the `Supplier`, `Product`, `OrderItem`, `Orders`, and `Customer` tables.
select * from orders;
select * from orderitem;
select * from supplier;
select * from product;
select * from customer;

-- Q2.  **Customer Demographics:** Find the count of customers in each country, ordered from highest to lowest.
select country, count(id) from customer
group by country
order by count(id) desc;

-- Q3.  **Active Inventory:** Display all products that are currently active (not discontinued).
select * from product
where isdiscontinued = "1";

-- Q4.  **Supplier Catalog:** List all company names along with the names of the products they supply.
select s.companyname, p.productname from supplier s
join product p
on s.id = p.supplierid;

-- Q5.  **Regional Search:** Find all customer information for those residing in 'Mexico'.
select * from customer
where country = "Mexico";

-- Q6.  **High-Value Items:** Identify the most expensive item ordered by each customer.
select c.id as customerid, p.productname, p.unitprice from customer c
join orders o
on c.id = o.customerid
join orderitem oi
on oi.orderid = o.id
join product p
on p.id = oi.productid
where (c.id, p.unitprice) in (
select c.id, max(p.unitprice) as most_expensive from product p
join orderitem oi
on oi.productid = p.id
join orders o
on o.id = oi.orderid
join customer c
on c.id = o.customerid
group by c.id
);

-- Q7.  **Top Suppliers:** Find the Supplier ID that provides the highest number of products.     { CTE }
with highest_product as (
select s.id, count(p.id) as count_product from supplier s
join product p
on s.id = p.supplierid
group by s.id
)
select * from highest_product
where count_product in ( select max(count_product) from highest_product);

-- Q8.  **Order Trends:** Display the count of orders placed each month and year.
select year(orderdate) as year, month(orderdate) as month, count(id) as order_count from orders
group by year(orderdate), month(orderdate)
order by year asc, month asc;

-- Q9.  **Supplier Concentration:** Which country has the maximum number of suppliers?
with max_number_supplier as ( 
select country, count(id) as supplier_count from supplier
group by country)
select distinct * from max_number_supplier
where supplier_count in (select max(supplier_count) from max_number_supplier);

/* WITH max_c AS (
    SELECT country, COUNT(id) OVER(PARTITION BY country) AS count
    FROM supplier
)
SELECT DISTINCT * FROM max_c 
WHERE count IN (SELECT MAX(count) FROM max_c); */

-- Q10. **Inactive Customers:** Identify customers who have never placed an order.
select * from customer c
where not exists (
select id from orders o
where c.id = o.customerid
);



										     -- ## Section B: Level 2 (Intermediate Queries)
                                             -- *Focus: JOINS, AGGREGATIONS, LIMIT, WINDOW FUNCTIONS*

 -- Q1. Arrange the Product ID and Name based on the high demand by the customer
select p.id, p.productname, count(quantity) as high_demand from product p
join orderitem oi
on p.id = oi.productid
group by p.id, p.productname
order by high_demand desc;

-- Q2. Display the total number of orders delivered every year
select count(id) as total_order, year(orderdate) as year from orders
group by year;

-- Q3.  **Revenue Analysis:** Calculate the total revenue generated each year.
select year(orderdate) as year, sum(totalamount) as total_revenue from orders
group by year(orderdate);

-- Q4.  **Top Spender:** Find the details of the customer who has spent the most money across all their orders.
select c.*, sum(o.totalamount) as most_money from customer c
join orders o
on c.id = o.customerid
group by c.id
order by most_money desc
limit 1 ;

-- Q5.  **Customer Ranking:** List all customers and their total order amounts, ordered from highest to lowest.
select c.*, sum(totalamount) as total_order_amounts from customer c
join orders o
on c.id = o.customerid
group by c.id
order by total_order_amounts desc;

-- Q6.  **Order History:** For each customer, list their current and previous order dates to see how frequently they do business.
select c.id as customerid, c.firstname, o.orderdate from customer c
join orders o 
on c.id = o.customerid
group by customerid, orderdate;

-- Q7.  **Supplier Revenue:** Identify the top 3 suppliers based on the total revenue generated by their products.
select s.id, s.contactname , sum(quantity * oi.unitprice) as total_revenue from supplier s
join product p
on s.id = p.supplierid
join orderitem oi
on p.id = oi.productid
join orders o
on o.id = oi.orderid
group by s.id, s.contactname
order by total_revenue desc
limit 3;

-- Q8.  **Customer Loyalty:** Display the latest order date for each customer (excluding their very first order).
select c.*, max(o.orderdate) as latest_order_date from customer c
join orders o 
on c.id = o.customerid
group by c.id;

-- Q9.  **Order Details:** For every order, display the Order ID, Product Name, and Supplier Name.
select o.id as order_id, p.productname as product_name, s.contactname as supplier_name from orders o
join orderitem oi
on o.id = oi.orderid
join product p 
on p.id = oi.productid
join supplier s 
on s.id = p.supplierid;





															-- ## Section C: Level 3 (Advanced Queries)
															-- *Focus: WITH (CTE), COMPLEX JOINS, SUBQUERIES*

-- Q1.  **Bulk Buyers:** Find customers who have ordered more than 10 products in a single order.
with single_order as (select distinct c.*, count(o.id) as order_id from customer c
join orders o 
on c.id = o.customerid
group by c.id)
select * from single_order
having order_id > 10
order by order_id desc;

			/*		-- CTE AND WINDOW FUNCTION
                    with cte_and_window as (
                    select distinct c.*, count(o.id) over (partition by c.id) as count_order_id from customer c
                    join orders o 
                    on c.id = o.customerid)
                    select * from cte_and_window 
                    where count_order_id > 10
                    order by count_order_id desc;
              */      

-- Q2.  **Small Orders:** List all product details for items that were ordered with a quantity of exactly 1.
select p.* from product p
join orderitem oi
on p.id = oi.productid
where quantity = 1;

-- Q3.  **Premium Suppliers:** Identify companies that supply products with a unit price above 100.
select distinct s.* from supplier s
join product p
on s.id = p.supplierid
join orderitem oi
on p.id = oi.productid
where oi.unitprice > 100;

-- Q4.  **City-Based Networking:** List customers who live in the same city and country, arranged by country.
select distinct c1.id, c1.firstname, c2.firstname, c1.city, c1.country from customer c1
join customer c2
on c1.city = c2.city   and    c1.country = c2.country
where c1.id <> c2.id
order by c1.country;





														-- ## Section D: Level 4 (Expert Queries)
														-- *Focus: COMPLEX CALCULATIONS, BUSINESS LOGIC*
					
-- Q1.  **Savings Analysis:** The company offers discounts. Calculate the total amount saved in each order (Actual Price - Selling Price) and rank orders by total savings.
select oi.orderid, sum((p.unitprice - oi.unitprice)*oi.quantity) as total_amt_saved from product p 
join orderitem oi
on p.id = oi.productid
group by oi.orderid
order by total_amt_saved desc;

/* Q2.  **Market Research:** Help a new supplier, Mr. Kavin, by identifying:
*   a. A list of high-demand products he should consider supplying.
*   b. A list of his potential competitors for those products. */
									-- HIGH-DEMAND PRODUCTS
                                    select p.productname, sum(oi.quantity) as high_demand from product p 
                                    join orderitem oi
                                    on p.id = oi.productid
                                    group by p.productname
                                    order by high_demand desc;
                                    
			    -- COMPETITORS FOR HIGH-DEMAND PRODUCT
				select distinct s.contactname, p.productname from product p
                join supplier s 
                on s.id = p.supplierid
                join orderitem oi
                on p.id = oi.productid;
                
                
                